version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: videoserver-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  server:
    build: ./server
    container_name: videoserver-backend
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - mongo

  client:
    build: ./client
    container_name: videoserver-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - server

volumes:
  mongo_data:
